trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_ecal_correlation.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_hcal_correlation.png")

trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation_trkfake0.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_ecal_correlation_trkfake0.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_hcal_correlation_trkfake0.png")

trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation_trkfake1.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_ecal_correlation_trkfake1.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_hcal_correlation_trkfake1.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10","hist same")
c1->SaveAs("sigmaptpt_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&trkNHit<30","hist same")
c1->SaveAs("nhits_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20","hist same")
c1->SaveAs("sigmaptpt_10_20.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&trkNHit<30","hist same")
c1->SaveAs("nhits_10_20.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_10_20.png")


trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100","hist same")
c1->SaveAs("sigmaptpt_20_100.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&trkNHit<30","hist same")
c1->SaveAs("nhits_20_100.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_20_100.png")

