trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_ecal_correlation.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5","colz")
c1->SaveAs("mtrk_hcal_correlation.png")

trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation_trkfake0.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_ecal_correlation_trkfake0.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5&&trkFake==0","colz")
c1->SaveAs("mtrk_hcal_correlation_trkfake0.png")

trackTree->Draw("(mtrkPfSumHcal+mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal+mtrkPfSumEcal)<100&&(mtrkPfSumHcal+mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_sumecalhcal_correlation_trkfake1.png")
trackTree->Draw("(mtrkPfSumEcal):mtrkPt","mtrkPt<100&&(mtrkPfSumEcal)<100&&(mtrkPfSumEcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_ecal_correlation_trkfake1.png")
trackTree->Draw("(mtrkPfSumHcal):mtrkPt","mtrkPt<100&&(mtrkPfSumHcal)<100&&(mtrkPfSumHcal)>1&&mtrkPt>0.5&&trkFake==1","colz")
c1->SaveAs("mtrk_hcal_correlation_trkfake1.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10","hist same")
c1->SaveAs("sigmaptpt_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&trkNHit<30","hist same")
c1->SaveAs("nhits_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>0.5&&trkPt<10&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_0_10.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20","hist same")
c1->SaveAs("sigmaptpt_10_20.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&trkNHit<30","hist same")
c1->SaveAs("nhits_10_20.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>10&&trkPt<20&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_10_20.png")


trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100","hist same")
c1->SaveAs("sigmaptpt_20_100.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&trkNHit<30","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&trkNHit<30","hist same")
c1->SaveAs("nhits_20_100.png")

trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkChi2/trkNdof","trkFake==0&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&(trkChi2/trkNdof)<5","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkChi2/trkNdof","trkFake==1&&trkPtError/trkPt<0.04&&trkPt>20&&trkPt<100&&(trkChi2/trkNdof)<5","hist same")
c1->SaveAs("chi2ndof_20_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt<10&&trkPt>0.5&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt<10&&trkPt>0.5&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","hist same")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_0_10.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt<20&&trkPt>10&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","hist")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt<20&&trkPt>10&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","hist same")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_10_20.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt<100&&trkPt>20&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt<100&&trkPt>20&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_20_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkDz1/trkDzError1>>htmp1","trkFake==0&&trkPt<100&&trkPt>20&&abs(trkDz1/trkDzError1)<150","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkDz1/trkDzError1>>htmp2","trkFake==1&&trkPt<100&&trkPt>20&&abs(trkDz1/trkDzError1)<150","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("dz_dzerr_20_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkDxy1/trkDxyError1>>htmp1","trkFake==0&&trkPt<100&&trkPt>20&&abs(trkDxy1/trkDxyError1)<150","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkDxy1/trkDxyError1>>htmp2","trkFake==1&&trkPt<100&&trkPt>20&&abs(trkDxy1/trkDxyError1)<150","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("dxy_dxyerr_20_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","abs(trkDz1/trkDzError1)<3&&trkPt<100&&trkPt>20&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","abs(trkDz1/trkDzError1)>20&&trkPt<100&&trkPt>20&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_dzdisc_20_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkNHit_50_300.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPt>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPt>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPt_50_300.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPt>>htmp1","trkFake==0&&trkPt>100&&trkPt<150","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPt>>htmp2","trkFake==1&&trkPt>100&&trkPt<150","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPt_100_150.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPt>>htmp1","trkFake==0&&trkPt>150&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPt>>htmp2","trkFake==1&&trkPt>150&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPt_150_300.png")



htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkEta>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkEta>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkEta_50_300.png")




htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPhi>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPhi>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPhi_50_300.png")





htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPt/trkPtError>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPt/trkPtError>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPt_trkPtError_50_300.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPtError/trkPt>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPtError/trkPt>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("trkPtError_trkPt_50_300.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt>50&&trkPt>100&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt>50&&trkPt>100&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_50_100.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt>100&&trkPt>150&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt>100&&trkPt>150&&(pfSumHcal+pfSumEcal)<200&&(pfSumHcal+pfSumEcal)>1&&(pfSumHcal+pfSumEcal)/trkPt<20","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_100_150.png")

htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt>50&&trkPt<100","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt>50&&trkPt<100","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_50_100.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt>100&&trkPt<150","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt>100&&trkPt<150","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_10_150.png")


htmp1->Delete()
htmp2->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp1","trkFake==0&&trkPt>150&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("(pfSumHcal+pfSumEcal)/trkPt>>htmp2","trkFake==1&&trkPt>150&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
c1->SaveAs("sumcalo_trkpt_150_300.png")




htmp1->Delete()
htmp2->Delete()
htmp3->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkNHit>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkNHit>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3005)
trackTree->SetFillColor(kGreen)
trackTree->Draw("trkNHit>>htmp3","(pfSumHcal+pfSumEcal)/trkPt>0.5&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
htmp3->DrawNormalized("same")
c1->SaveAs("trkNHit_50_300.png")

htmp1->Delete()
htmp2->Delete()
htmp3->Delete()
trackTree->SetFillStyle(3001)
trackTree->SetFillColor(kBlue)
trackTree->Draw("trkPt/trkPtError>>htmp1","trkFake==0&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3004)
trackTree->SetFillColor(kRed)
trackTree->Draw("trkPt/trkPtError>>htmp2","trkFake==1&&trkPt>50&&trkPt<300","goff")
trackTree->SetFillStyle(3005)
trackTree->SetFillColor(kGreen)
trackTree->Draw("trkPt/trkPtError>>htmp2","(pfSumHcal+pfSumEcal)/trkPt>0.5&&trkPt>50&&trkPt<300","goff")
htmp1->DrawNormalized()
htmp2->DrawNormalized("same")
htmp3->DrawNormalized("same")
c1->SaveAs("trkPt_trkPtError_50_300.png")
